# Generated by Django 4.0.5 on 2022-08-13 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_blood', models.BooleanField(default=False)),
                ('donate_blood', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalBloodDonationBE.message')),
                ('recipient_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='AnimalBloodDonationBE.owner')),
                ('sender_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='AnimalBloodDonationBE.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Animal', max_length=50)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='static/pet_images/')),
                ('breed', models.CharField(default='Unknown', max_length=50)),
                ('blood_type', models.CharField(default='Unknown', max_length=10)),
                ('region', models.CharField(default='Not specified', max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalBloodDonationBE.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalBloodDonationBE.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/case_images/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('case_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalBloodDonationBE.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='pet_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimalBloodDonationBE.pet'),
        ),
    ]
